name: WirelessRedstone
main: net.licks92.WirelessRedstone.WirelessRedstone
website: http://dev.bukkit.org/server-mods/wireless-redstone/
author: licks92
version: 1.5.2b
description: A plugin for Bukkit that makes Wireless Redstone Connections! Original project by Wmisiedjan
commands:
   wrhelp:
      aliases: [wirelessredstone]
      description: WirelessRedstone help menu
      usage: |
             Example: /<command>
   wrt:
      aliases: [wrtransmitter]
      description: Creates a transmitter sign with given channel
      usage: |
             Example: /<command> Channel1
   wrr:
      aliases: [wrreceiver]
      description: Creates a receiver sign with given channel
      usage: |
             Example: /<command> Channel1
   wri:
      aliases: [wrinfo]
      description: Channel informations
      usage: |
             Example: /<command> Channel1
   wrc:
      description: Channel admin commands
      usage: |
             Example: /<command> subcommand
   wrremove:
      description: Remove a channel with all its signs!
      usage: |
             Example: /<command> subcommand
   wrlist:
      description: Lists all channels!
      usage: |
             Example: /<command> page